const Hotlink_Postpaid_Mobile_Plan_Key = "HotlinkPostpaid_MobilePlan"
const Hotlink_Postpaid_Mobile_Plan_Details_Key = "HotlinkPostpaid_MobilePlan_Details"
const Hotlink_Postpaid_Fibre_Broadband_Plan_key = "HotlinkPostpaid_FibreBroadbandPlan"
const Hotlink_Postpaid_Fibre_Bundled_Plan_key = "HotlinkPostpaid_FibreBundledPlan"
const Hotlink_Prepaid_Mobile_Plan_Key = "HotlinkPrepaid_MobilePlan"
const Hotlink_Prepaid_Switch_Plan_Key = "HotlinkPrepaid_SwitchPlan"
const Brand_Devices_Key = "Brand_Devices"
const Brand_Tablets_Key = "Brand_Tablets "
const Brand_Wearables_Key = "Brand_Wearables "
const Contract_Devices_Key = "Contract_Devices"
const Contract_Tablets_Key = "Contract_Tablets"
const Contract_Wearables_Key = "Contract_Wearables"
const Promo_Devices_Key = "Promo_Devices"
const Promo_Tablets_Key = "Promo_Tablets"
const Promo_Wearables_key = "Promo_Wearables"
const HotlinkPostpaid_Brand_Key = "HotlinkPostpaid_Brand"
const HotlinkPostpaid_Promo_Key = "HotlinkPostpaid_Promo"
const States_List_Key = "States_List"
const HotlinkPostpaid_LatestDevices_Key = "HotlinkPostpaid_LatestDevices"
const HotlinkPostpaid_LatestPromotions_Key = "HotlinkPostpaid_LatestPromotions"
const MaxisPostpaid_Broadband_FamilyPlans_Key = "MaxisPostpaid_Broadband_Family_Plans"
const Store_List = "Store_List"

module.exports.Hotlink_Postpaid_Mobile_Plan_Key = Hotlink_Postpaid_Mobile_Plan_Key
module.exports.Hotlink_Postpaid_Mobile_Plan_Details_Key = Hotlink_Postpaid_Mobile_Plan_Details_Key
module.exports.Hotlink_Postpaid_Fibre_Broadband_Plan_key = Hotlink_Postpaid_Fibre_Broadband_Plan_key
module.exports.Hotlink_Postpaid_Fibre_Bundled_Plan_key = Hotlink_Postpaid_Fibre_Bundled_Plan_key
module.exports.Hotlink_Prepaid_Mobile_Plan_Key = Hotlink_Prepaid_Mobile_Plan_Key
module.exports.Hotlink_Prepaid_Switch_Plan_Key = Hotlink_Prepaid_Switch_Plan_Key
module.exports.Brand_Devices_Key = Brand_Devices_Key
module.exports.Brand_Tablets_Key = Brand_Tablets_Key
module.exports.Brand_Wearables_Key = Brand_Wearables_Key
module.exports.Contract_Devices_Key = Contract_Devices_Key
module.exports.Contract_Tablets_Key = Contract_Tablets_Key
module.exports.Contract_Wearables_Key = Contract_Wearables_Key
module.exports.Promo_Devices_Key = Promo_Devices_Key
module.exports.Promo_Tablets_Key = Promo_Tablets_Key
module.exports.Promo_Wearables_key = Promo_Wearables_key
module.exports.HotlinkPostpaid_Brand_Key = HotlinkPostpaid_Brand_Key
module.exports.HotlinkPostpaid_Promo_Key = HotlinkPostpaid_Promo_Key
module.exports.States_List_Key = States_List_Key
module.exports.HotlinkPostpaid_LatestDevices_Key = HotlinkPostpaid_LatestDevices_Key
module.exports.HotlinkPostpaid_LatestPromotions_Key = HotlinkPostpaid_LatestPromotions_Key
module.exports.MaxisPostpaid_Broadband_FamilyPlans_Key = MaxisPostpaid_Broadband_FamilyPlans_Key
module.exports.Store_List = Store_List
