const { ApiError } = require('@google-cloud/storage/build/src/nodejs-common');
const API = require('./Handler_Webhook');

// "Billing.ChangeCreditLimit.CurrentCreditLimit.QueryNew.Increase" : API.Billing_ChangeCreditLimit_CurrentCreditLimit_QueryNew_Increase,
// "Billing.ChangeCreditLimit.CurrentCreditLimit.QueryNew.Decrease" :API.Billing_ChangeCreditLimit_CurrentCreditLimit_QueryNew_Decrease,
// "Sales.PurchaseDevice.DiscoveryBrand.Color2"      : API.Sales_PurchaseDevice_DiscoveryBrand_Color,
// "Sales.PurchaseDevice.DiscoveryBrand"             : API.Sales_PurchaseDevice_DiscoveryBrand,

exports.Map = function() {
  return {
    //-----------------------------------------------------------
    // âœ¨ INTENT MAPPER
    //-----------------------------------------------------------
    // INTENT NAME                                     HANDLER-API
    /** *********
         * Multi channel intent info
         */
    'Greeting.Start1': API.Greeting_Start1,
    'Greeting.Start': API.Greeting_Start,
    'Shared.Profile.DisplayName': API.Shared_Profile_DisplayName,
    'Default': API.Default,
    'Shared.FollowUpEvent.1': API.Shared_FollowUpEvent,
    'Shared.FollowUpEvent.Star': API.Shared_FollowUpEvent,
    'Shared.Menu.Start.1': API.Shared_Menu_Start_1,
    'Greeting.Authentication.MobileNo.Input.Query': API.Greeting_Authentication_MobileNo_Input_Query,

    'Shared.Auth.ExistingTAC': API.Auth_EnterTAC,
    'Shared.Auth.EnterTAC': API.Auth_EnterTAC,
    'Shared.Auth.InvalidTAC': API.Auth_InvalidTAC,
    'Shared.Auth.ResendTAC': API.Shared_Auth_ResendTAC,

    'Shared.Closure': API.Shared_Closure,
    'Shared.Closure.HelpfulYes': API.Shared_Closure_HelpfulYes,
    'Shared.Closure.HelpfulNo': API.Shared_Closure_HelpfulNo,

    'Shared.CS.BusinessHour': API.Shared_CS_BusinessHour,
    'Shared.Agent.Servicing.Handover': API.Shared_Agent_Servicing_Handover,
    'Shared.Agent.Network.Handover': API.Shared_Agent_Network_Handover,
    'Shared.Agent.Servicing.Handover.any': API.Shared_Agent_Servicing_Handover,
    'Shared.Agent.Telesales.Servicing.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,

    'Greeting.GeneralBM': API.Shared_Agent_Servicing_Handover_BM,

    'Mobile&BroadbandSubscription.GovernmentIndividual.MaxisPostpaid60.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Mobile&BroadbandSubscription.GovernmentIndividual.MaxisPostpaid98.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Mobile&BroadbandSubscription.GovernmentIndividual.MaxisPostpaid128.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Mobile&BroadbandSubscription.GovernmentIndividual.MaxisPostpaid158.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Mobile&BroadbandSubscription.GovernmentIndividual.MaxisPostpaid188.Handover': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Mobile&BroadbandSubscription.Prepaid.HotlinkPostpaid': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,

    // "Billing.CheckBillingInfo.StoreCustomerInfo":API.Billing_CheckBillingInfo_StoreCustomerInfo,
    // "Billing.AccountStatus"                           : API.Billing_AccountStatus,
    // "Billing.AccountStatus.Active.End"                : API.Billing_ContractInfo,
    // "Billing.CheckBillingInfo.RetrieveContractInfo"    :API.Billing_CheckBillingInfo_RetrieveContractInformation,

    'Billing.CheckBillingInfo.StoreCustomerInfo': API.Billing_CheckBillingInfo_StoreCustomerInfo,

    'Billing.AccountStatus': API.Billing_AccountStatus,
    'Billing.AccountStatus.Active.End': API.Billing_ContractInfo,
    // "Billing.AccountStatus.Active.End.Naked"          : API.Contract_Info_Naked_Fibre,
    'Billing.BillStatementRequest': API.Billing_BillStatementRequest,

    'Billing.BillStatementRequest.QueryEBill.QueryMonth': API.Billing_BillStatementRequest_QueryEBill_QueryMonth,
    'Billing.BillStatementRequest.Itemised.QueryMonth': API.Billing_BillStatementRequest_Itemised_QueryMonth,
    'Billing.BillStatementRequest.Itemised.OtherMonth': API.Billing_BillStatementRequest_Itemised_OtherMonth,
    'Billing.BillStatementRequest.Summarised.QueryMonth': API.Billing_BillStatementRequest_Summary_QueryMonth,
    'Billing.BillStatementRequest.Summarised.OtherMonth': API.Billing_BillStatementRequest_Summary_OtherMonth,

    'Billing.ChangeCreditLimit': API.Billing_ChangeCreditLimit,
    'Billing.ChangeCreditLimit.IncreaseCreditLimit.Confirmation.Yes': API.Billing_ChangeCreditLimit_IncreaseCreditLimit_Confirmation_Yes,
    'Billing.ChangeCreditLimit.DecreaseCreditLimit.Confirmation.Yes': API.Billing_ChangeCreditLimit_DecreaseCreditLimit_Confirmation_Yes,




    'Sales.PurchaseDevice.LatestPromo.Selection': API.Sales_PurchaseDevice_LatestPromo_Selection,

    'Sales.PurchaseDevice.DiscoveryBrand.Start': API.Sales_PurchaseDevice_DiscoveryBrand,
    'Sales.PurchaseDevice.DiscoveryBrand.DeviceList': API.Sales_PurchaseDevice_DiscoveryBrand_DeviceList,

    'Sales.PurchaseDevice.DiscoveryBrand.ModelSelection': API.Sales_PurchaseDevice_DiscoveryBrand_Capacity,
    'Sales.PurchaseDevice.DiscoveryBrand.CapacitySelection': API.Sales_PurchaseDevice_DiscoveryBrand_Color,
    'Sales.PurchaseDevice.DiscoveryBrand.ColorSelection': API.Sales_PurchaseDevice_DiscoveryBrand_Contract,

    'Sales.PurchaseDevice.DiscoveryBrand.ContractSelection': API.Sales_PurchaseDevice_DiscoveryBrand_RatePlan,
    'Sales.PurchaseDevice.DiscoveryBrand.RatePlanSelection': API.Sales_PurchaseDevice_DiscoveryBrand_SKUSummary,
    'Sales.PurchaseDevice.DiscoveryBrand.Sku.YesAddCart': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Checkout,

    'Sales.PurchaseDevice.DiscoveryBrand.SKUSummary': API.Sales_PurchaseDevice_DiscoveryBrand_SKUSummary,
    'Sales.PurchaseDevice.DiscoveryBrand.SKUSummary.Proceed': API.Sales_PurchaseDevice_DiscoveryBrand_SKUSummary_Proceed,
    'Sales.PurchaseDevice.DiscoveryOffer.SKUSummary.Proceed.Options': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Options,
    'Sales.Purchase.Device.DiscoveryOffer.SKUSummary.Proceed.TeleSales': API.Sales_PurchaseDevice_DiscoveryOffer_SKUSummary_Proceed_Telesales,
    'Sales.DiscoverAndPurchase.TechIssue.End': API.Sales_DiscoverAndPurchase_TechIssue_End,

    'Recontracting.Start': API.Recontracting_Start,
    'Recontracting.DeviceDiscovery': API.Recontracting_DeviceDiscovery,
    'AccMgt.PUK.PresentPUK': API.AccMgt_PUK_PresentPUK,
    'Paybill.Menu.Query' : API.Paybilss_Topup_Menu_Query,
    'Billing.PayBill.SelectAccount.Tac' : API.Billing_PayBill_SelectAccount_Tac,
    'Billing.PayBill.SelectOtherPayment': API.Billing_SelectOtherPayment,
    'Billing.PayBill.OtherAccount' : API.Billing_OtherAccount,
    'Billing.Payment.TerminatedAcc.Verification' : API.Billing_TerminatedAccount,
    'Billing.Payment.TerminatedAcc.Verification.Failed' : API.Shared_Closure_Entry,
    'Billing.Payment.TerminatedAcc.Verified.PresentBillDetails.NoWriteOff': API.Shared_Closure_Entry,
    'Billing.Payment.TerminatedAcc.Verified.PresentBillDetails.HasWriteOff': API.Shared_Closure_Entry,
    'Billing.Payment.TerminatedAcc.Verified.PresentBillDetails.NoWriteOff.NoOutstanding': API.Shared_Closure_Entry,
    'Billing.Payment.TerminatedAcc.Verified.PresentBillDetails.HasWriteOff.HasLODSummon': API.Billing_AgentHandover,
    'Billing.Payment.TerminatedAcc.Verified.PresentBillDetails.NoWriteOff.HasLODSummon': API.Billing_AgentHandover,
    'Billing.Payment.TerminatedAcc.Verified.AgentAssistOffer.Yes': API.Billing_AgentHandover_Yes,
    'Billing.Payment.TerminatedAcc.Verified.AgentAssistOffer.No': API.Shared_Closure_Entry,
    'Billing.PayBill.MakeOtherPayment.Retry.Yes' : API.Billing_SelectOtherPayment,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Ok.TooManyDevices.MeshWifi' : API.TooManyDevices_MeshWifi,
    'Billing.PayBill.Olo.Tac' : API.Billing_PayBill_Olo_Tac,
    'Billing.RetrievePaymentReceipts.NoPaymentRecord.END' : API.Shared_Closure_Entry,
    'Billing.RetrievePaymentReceipts' : API.Billing_RetrievePaymentReceipts,
    'Billing.RetrievePaymentReceipts.MonthYear' : API.Billing_RetrievePaymentReceipts_MonthYear,
    'Billing.RetrievePaymentReceipts.CreateReceipt': API.RetrievePaymentReceipts_CreateReceipt,
    'Billing.RetrievePaymentReceipts.AnotherReceipt.Retry.Yes' : API.RetrievePaymentReceipts_AnotherReceipt_Retry_Yes,

    'Billing.ChangeBillCycle.CurrentBC': API.Billing_ChangeBillCycle_CurrentBC,
    'Billing.ChangeBillCycle.CurrentBC3': API.Billing_ChangeBillCycle_CurrentBC,
    'Billing.ChangeBillCycle.QueryBC': API.Billing_ChangeBillCycle_QueryBC,
    'Billing.ChangeBillCycle.ConfirmChange': API.Billing_ChangeBillCycle_ConfirmChange,

    'Billing.MakePayment': API.Billing_MakePayment,
    'Billing.MakePayment.1': API.Billing_MakePayment,
    'Billing.DirectDebit': API.Billing_DirectDebit,
    'Billing.MakePayment.DirectDebitOffer.Yes': API.Billing_MakePayment_DirectDebitOffer,

    'ProactiveCaseUpdate.Start': API.ProactiveCaseUpdate_Start,
    'ProactiveCaseUpdate.Present.CSHandover': API.ProactiveCaseUpdate_Present_CSHandover,
    'ProactiveCaseUpdate.AgentHandover.CustomerServiceQuery': API.ProactiveCaseUpdate_AgentHandover_CustomerServiceQuery,

    'CaseStatus.Start': API.CaseStatus_Start,

    'Billing.eBill': API.Billing_eBill,
    'Billing.ebill.2': API.Billing_eBill,
    'Biling.eBill.NotRegistered.EmailQuery': API.Biling_eBill_NotRegistered_EmailQuery,
    'Billing.eBill.Verification.Resend': API.Billing_eBill_Verification_Resend,
    'Biling.eBill.Registered.NewEmail': API.Biling_eBill_Registered_NewEmail,
    'Biling.eBill.NotRegistered.End': API.Shared_Closure_Entry,

    'Profile.BillingAddress': API.Profile_BillingAddress,
    'Profile.BillingAddress.CurrentAddress': API.Profile_BillingAddress_CurrentAddress,
    'Profile.BillingAddress.ChangeAddress': API.Profile_BillingAddress_ChangeAddress,
    'Profile.BillingAddress.ChangeAddress.ReUpdate': API.Profile_BillingAddress_ChangeAddress,
    'Profile.BillingAddress.ChangeAddress.Confirmation.Yes': API.Profile_BillingAddress_ChangeAddress_Confirmation_Yes,
    'Profile.BillingAddress.ChangeAddress.Invalid': API.Profile_BillingAddress_ChangeAddress_Invalid,

    'Billing.TaxStatementRequest': API.Billing_TaxStatementRequest,
    'Billing.TaxStatementRequest.NoEbill.Year': API.Billing_TaxStatementRequest_NoEbill_Year,
    'Billing.TaxStatementRequest.EmailQuery.Year': API.Billing_TaxStatementRequest_EmailQuery_Year,
    'Billing.eBill.1': API.Billing_eBill,
    'Billing.TaxStatementRequest.EmailQuery.Yes': API.Billing_TaxStatementRequest_EmailQuery_Yes,
    'Billing.TaxStatementRequest.NoEbill.EmailAddress.EmailQuery': API.Billing_TaxStatementRequest_NoEbill_EmailAddress,

    'Network.Fibre.SlowWifi.DiagnosticCheck': API.Network_Fibre_SlowWifi_DiagnosticCheck,
    'Network.Fibre.SlowWifi.DiagnosticCheck.ModemId': API.Network_Fibre_SlowWifi_DiagnosticCheck_ModemId,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Yes': API.Network_Fibre_SlowWifi_DiagnosticCheck_Yes,

    'Shared.Bot.Fallback': API.Shared_Bot_Fallback,
    'Bypass': API.Shared_ByPass_Agent,
    'SharedAgent': API.Shared_ByPass_Agent,
    'Bypass Bot - Biilling.AccountStatus.SeekClarifircation': API.Shared_ByPass_Agent,

    'Network.Fibre.SlowWifi.DiagnosticCheck.Result': API.Network_Fibre_SlowWifi_DiagnosticCheck_Result,
    'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceYes': API.Network_Fibre_SlowWifi_DiagnosticCheck_DiagnosticError_AssistanceYes,
    //'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceNo': API.Network_Fibre_SlowWifi_DiagnosticCheck_DiagnosticError_AssistanceNo,
    'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceNo': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.PositiveResult.Assistance.No.Initiate': API.Network_Fibre_SlowWifi_DiagnosticCheck_PositiveResult_Assistance_No,

    'JaringanPrihatin.English.Eligibility': API.JaringanPrihatin_English_Eligibility,
    'JaringanPrihatin.NonMaxis.NRIC.Verify': API.JaringanPrihatin_NonMaxis_NRIC_Verify,
    'JaringanPrihatin.Eligible.Yes.DeviceSubsidy': API.JaringanPrihatin_Eligible_Yes_DeviceSubsidy,
    'JaringanPrihatin.Bm.Eligibility': API.JaringanPrihatin_Bm_Eligibility,
    'JaringanPrihatin.Bm.NonMaxis.NRIC.Verify': API.JaringanPrihatin_Bm_NonMaxis_NRIC_Verify,
    'JaringanPrihatin.Bm.Eligible.Yes.DeviceSubsidy': API.JaringanPrihatin_Bm_Eligible_Yes_DeviceSubsidy,

    'Greeting.ManageMyAccount.Start': API.Greeting_ManageMyAccount_Start,
    'Greeting.ManageMyProfile.Start': API.Greeting_ManageMyProfile_Start,
    'Billing.Content.Start': API.Billing_Content_Start,
    'Greeting.ManageMyAccount.BillStatement.Start': API.Greeting_ManageMyAccount_BillStatement_Start,
    'Greeting.DeviceDiscoverAndPurchase.Start': API.Greeting_DeviceDiscoverAndPurchase_Start,
    'Greeting.CheckCaseStatus.Start': API.Greeting_CheckCaseStatus_Start,
    'Greeting.Mobile&BroadbandSubscription.Start': API.Greeting_Mobile_BroadbandSubscription_Start,
    'Greeting.ManageFibreService.Start': API.Greeting_ManageFibreService_Start,
    'Billing.Manage.App.Store.start': API.Billing_Manage_App_Store_start,
    'Mobile&BroadbandSubscription.Prepaid.Start': API.Mobile_BroadbandSubscription_Prepaid_Start,
    'Mobile&BroadbandSubscription.Broadband.Start': API.Mobile_BroadbandSubscription_Broadband_Start,
    'Mobile&BroadbandSubscription.GovernmentIndividual.Start': API.Mobile_BroadbandSubscription_GovernmentIndividual_Start,
    'Profile.DID.SelfServe.Start': API.Profile_DID_SelfServe_Start,
    'MobileAndBroadbandSubscription.Postpaid.Start': API.MobileAndBroadbandSubscription_Postpaid_Start,
    'Billing.ChangeCreditLimit.IncreaseCreditLimit.Confirmation.Start': API.Billing_ChangeCreditLimit_IncreaseCreditLimit_Confirmation_Start,
    'Billing.ChangeCreditLimit.DecreaseCreditLimit.Confirmation.Start': API.Billing_ChangeCreditLimit_DecreaseCreditLimit_Confirmation_Start,
    'Billing.TaxStatementRequest.NoEbill.RegisterEbill.Start': API.Billing_TaxStatementRequest_NoEbill_RegisterEbill_Start,
    'Billing.BillStatementRequest.QueryEBill.No.BillCharged.Start': API.Billing_BillStatementRequest_QueryEBill_No_BillCharged_Start,
    'Billing.BillStatementRequest.QueryEBill.Yes.Start': API.Billing_BillStatementRequest_QueryEBill_Yes_Start,
    'Billing.ChangeCreditLimit.IncreaseCreditLimit.Confirmation': API.Billing_ChangeCreditLimit_IncreaseCreditLimit_Confirmation,
    'Billing.ChangeCreditLimit.DecreaseCreditLimit.Confirmation': API.Billing_ChangeCreditLimit_DecreaseCreditLimit_Confirmation,
    'Mobile&BroadbandSubscription.Postpaid.Family': API.MobileBroadbandSubscription_Postpaid_Family,
    'Mobile&BroadbandSubscription.Postpaid.Business': API.MobileBroadbandSubscription_Postpaid_Business,
    'Mobile&BroadbandSubscription.Postpaid.Personal': API.MobileBroadbandSubscription_Postpaid_Personal,
    'Mobile&BroadbandSubscription.Broadband.Home': API.MobileBroadbandSubscription_Broadband_Home,
    'Mobile&BroadbandSubscription.Broadband.Business': API.MobileBroadbandSubscription_Broadband_Business,
    'Mobile&BroadbandSubscription.Broadband.OnTheGo': API.MobileBroadbandSubscription_Broadband_OnTheGo,

    'SMEGrant.Q1.Yes': API.SMEGrant_Q1_Yes,
    'SMEGrant.Q1.No': API.SMEGrant_Q1_No,
    'SMEGrant.Bm.Q1.Yes': API.SMEGrant_BM_Q1_Yes,
    'SMEGrant.Bm.Q1.No': API.SMEGrant_BM_Q1_No,
    'Petronas.En.Language.Wh': API.Petronas_En_Language_Wh,
    // 'Petronas.Bm.Language.Wh': API.Petronas_En_Language_Wh,
    'Petronas.En.Language.Back.Wh': API.Petronas_En_Language_Wh,
    // 'Petronas.Bm.Language.Back.Wh': API.Petronas_En_Language_Wh,
    'Petronas.En.CustomerType.Existing.Wh': API.Petronas_En_CustomerType_Existing_Wh,
    'Petronas.En.CustomerType.New.Wh': API.Petronas_En_CustomerType_New_Wh,
    'Petronas.En.Plan.FibreBundle.Wh': API.Petronas_En_Plan_FibreBundle_Wh,
    'Petronas.En.Plan.WiFiBundle.Wh': API.Petronas_En_Plan_WiFiBundle_Wh,
    'Petronas.En.Plan.Postpaid.Wh': API.Petronas_En_Plan_WiFiBundle_Wh,
    'Petronas.En.Plan.Broadband.Wh': API.Petronas_En_Plan_WiFiBundle_Wh,

    'Petronas.En.PlanFibre.300.Wh': API.Petronas_En_PlanFibre_100_Wh,
    'Petronas.En.PlanFibre.500.Wh': API.Petronas_En_PlanFibre_100_Wh,
    'Petronas.En.PlanFibre.800.Wh': API.Petronas_En_PlanFibre_100_Wh,
    'Petronas.En.CustomerDetails.Wh': API.Petronas_En_CustomerDetails_Wh,

    'Petronas.Bm.Language.Wh': API.Petronas_Bm_Language_Wh,
    'Petronas.Bm.Language.Back.Wh': API.Petronas_Bm_Language_Wh,
    'Petronas.Bm.CustomerType.Existing.Wh': API.Petronas_Bm_CustomerType_Existing_Wh,
    'Petronas.Bm.CustomerType.New.Wh': API.Petronas_Bm_CustomerType_New_Wh,
    'Petronas.Bm.Plan.FibreBundle.Wh': API.Petronas_Bm_Plan_FibreBundle_Wh,
    'Petronas.Bm.Plan.WiFiBundle.Wh': API.Petronas_Bm_Plan_WiFiBundle_Wh,
    'Petronas.Bm.Plan.Postpaid.Wh': API.Petronas_Bm_Plan_WiFiBundle_Wh,
    'Petronas.Bm.Plan.Broadband.Wh': API.Petronas_Bm_Plan_WiFiBundle_Wh,

    'Petronas.Bm.PlanFibre.300.Wh': API.Petronas_Bm_PlanFibre_100_Wh,
    'Petronas.Bm.PlanFibre.500.Wh': API.Petronas_Bm_PlanFibre_100_Wh,
    'Petronas.Bm.PlanFibre.800.Wh': API.Petronas_Bm_PlanFibre_100_Wh,
    'Petronas.Bm.CustomerDetails.Wh': API.Petronas_Bm_CustomerDetails_Wh,

    'iPhone13.En.CustomerDetails.Wh': API.iPhone13_En_CustomerDetails_Wh,
    'iPhone13.Bm.CustomerDetails.Wh': API.iPhone13_Bm_CustomerDetails_Wh,

    'Sfdc.En.CompanyEligibility.Wh': API.Sfdc_En_CompanyEligibility_Wh,
    'Sfdc.En.CompanyRegion.Wh': API.Sfdc_En_CompanyRegion_Wh,
    'Sfdc.En.CompanyRegionCentral.Wh': API.Sfdc_En_CompanyRegionCentral_Wh,
    'Sfdc.En.CompanyRegionSouthern.Wh': API.Sfdc_En_CompanyRegionSouthern_Wh,
    'Sfdc.En.CompanyRegionNorthern.Wh': API.Sfdc_En_CompanyRegionNorthern_Wh,
    'Sfdc.En.CompanyRegionEastCoast.Wh': API.Sfdc_En_CompanyRegionEastCoast_Wh,
    'Sfdc.En.CompanyRegionSabah.Wh': API.Sfdc_En_CompanyRegionSabah_Wh,
    'Sfdc.En.CompanyDetails': API.Sfdc_En_CompanyDetails,

    'Sfdc.Bm.CompanyEligibility.Wh': API.Sfdc_Bm_CompanyEligibility_Wh,
    'Sfdc.Bm.CompanyRegion.Wh': API.Sfdc_Bm_CompanyRegion_Wh,
    'Sfdc.Bm.CompanyRegionCentral.Wh': API.Sfdc_Bm_CompanyRegionCentral_Wh,
    'Sfdc.Bm.CompanyRegionSouthern.Wh': API.Sfdc_Bm_CompanyRegionSouthern_Wh,
    'Sfdc.Bm.CompanyRegionNorthern.Wh': API.Sfdc_Bm_CompanyRegionNorthern_Wh,
    'Sfdc.Bm.CompanyRegionEastCoast.Wh': API.Sfdc_Bm_CompanyRegionEastCoast_Wh,
    'Sfdc.Bm.CompanyRegionSabah.Wh': API.Sfdc_Bm_CompanyRegionSabah_Wh,
    'Sfdc.Bm.CompanyDetails': API.Sfdc_Bm_CompanyDetails,

    'MultiCampaign': API.MultiCampaign,

    'PrepaidTopup.TopupMenu': API.PrepaidTopup_TopupMenu,
    'PrepaidTopup.TopupHistory': API.PrepaidTopup_TopupHistory,
    'PrepaidTopup.AcceptTopup.Yes': API.PrepaidTopup_AcceptTopUp_Yes,
    'PrepaidTopup.AcceptTopup.No - yes': API.PrepaidTopup_AcceptTopUp_No_yes,

    // "PrepaidTopup.PerformTopup" : API.PrepaidTopup_PerformTopup,
    // "PrepaidTopup.iShare" : API.PrepaidTopup_iShare,
    'Hybrid.DeviceDiscovery': API.HybridBot_DeviceDiscovery,
    // "Hybrid.Start.Postpaid": API.HybridBot_LanguageSelection,
    'Hybrid.Select.Language': API.HybridBot_LanguageSelection,
    // "Hybrid.Select.Language.En": API.HybridBot_LanguageSelection_En,
    // "Hybrid.Select.Language.Bm": API.HybridBot_LanguageSelection_Bm,
    // "PrepaidTopup.PerformTopup" : API.PrepaidTopup_PerformTopup,
    'PrepaidTopup.iShare.FAQ.Query': API.PrepaidTopup_iShare_FAQ_Query,
    // MVP2

    // "ManageRouter.Start" : API.ManageRouter_Start,
    'ManageRouter.Start.Reboot.RouterReboot': API.ManageRouter_Start_Reboot,
    'ManageRouter.Start.Reboot.ChangeWifi': API.ManageRouter_Start_changeWifi,
    // "ManageRouter.Start.RescheduleReboot" : API.ManageRouter_Start,
    'RouterReboot.FibreId': API.Router_reboot_fibreid,
    // "RouterReboot.Complete": API.Router_reboot_complete,
    // // "RouterReboot.Schedule.Frequency.Day.Time.Confirm":API.Router_reboot_freq_selection,
    // "RouterReboot.Schedule.Frequency.Day.Time.Confirm.No":API.ScheduleReboot_now,
    // "RouterReboot.Schedule.Frequency.Day.Time.UpdateACS": API.Router_reboot_updateACS,
    // // "ManageRouter.Select": API.ManageRouter_Select,
    // // "RouterReboot.NRIC.Verify": API.Router_reboot_NRIC_Verify,

    // "ManageRouter.Start.ChangeWifiSetting": API.ManageRouter_Start_ChangeWifi,
    // "ChangeWifi.FibreId": API.Change_Wifi_fibreid,
    // "ChangeWifi.Password.NewPassword.Confirm.Wh" : API.ChangeWifi_Password_NewPassword_Confirm_Wh,
    // // "ChangeWifi.Name.NewName.Wh" : API.ChangeWifi_Name_NewName_Wh,
    // "ChangeWifi.Name.NewName.Confirm.Wh" : API.ChangeWifi_Name_NewName_Confirm_Wh,
    // 'ManageRouter.Start.Reboot.ChangeWifi-OLO': API.ManageRouter_Start_changeWifi,
    // 'ManageRouter.Start.Reboot.RouterReboot.OLO': API.ManageRouter_Start_Reboot,

    // Port out
    'DiscoverMaxisProductsServices.SwitchtoMaxisPostpaidMaxisHomeFibre.SubMenu.Input2': API.DiscoverMaxisProductsServices_SwitchtoMaxisPostpaidMaxisHomeFibre_SubMenu_Input2,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPostpaid.SubMenu.Input1': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPostpaid_SubMenu_Input1,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPrepaid.SubMenu.Input1': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPrepaid_SubMenu_Input1,
    'DiscoverMaxisProductsServices.SwitchtoMaxisPostpaidMaxisHomeFibre.SubMenu.Input1.PostPaid': API.DiscoverMaxisProductsServices_SwitchtoMaxisPostpaidMaxisHomeFibre_SubMenu_Input1_PostPaid,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPostpaid.SubMenu.Input1.PostPaid': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPostpaid_SubMenu_Input1_PostPaid,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPrepaid.SubMenu.Input1.PostPaid': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPrepaid_SubMenu_Input1_PostPaid,
    'DiscoverMaxisProductsServices.SwitchtoMaxisPostpaidMaxisHomeFibre.SubMenu.Input1.PrePaid': API.DiscoverMaxisProductsServices_SwitchtoMaxisPostpaidMaxisHomeFibre_SubMenu_Input1_PrePaid,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPostpaid.SubMenu.Input1.PrePaid': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPostpaid_SubMenu_Input1_PrePaid,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPrepaid.SubMenu.Input1.PrePaid': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPrepaid_SubMenu_Input1_PrePaid,
    'PortIn.StatusMSISDN.Query.RetrieveInfo': API.PortIn_StatusMSISDN_Query_RetrieveInfo,
    'PortIn.StatusMSISDN.Query.OtherMSISDN.Verify': API.PortIn_StatusMSISDN_Query_OtherMSISDN_Verify,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.MoreThan12Hours.RequestNRIC.Verify': API.PortIn_Status_InProcess_Maxis_CaseEscalation_MoreThan12Hours_RequestNRIC_Verify,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.ActivationMoreThan2Hours.RequestNRIC.Verify': API.PortIn_Status_InProcess_Maxis_CaseEscalation_ActivationMoreThan2Hours_RequestNRIC_Verify,
    'PortIn.Status.Rejected.7DayTimedOut': API.PortIn_Status_Rejected_7DayTimedOut,
    'PortIn.Status.Rejected.7DayTimedOut.PortIn.Yes': API.PortIn_Status_Rejected_7DayTimedOut_PortIn_Yes,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.MoreThan12Hours.RequestNRIC.VerifyNric': API.PortIn_Status_InProcess_Maxis_CaseEscalation_MoreThan12Hours_RequestNRIC_VerifyNric,

    // Port In Initiation
    'DiscoverMaxisProductsServices.SwitchtoMaxisPostpaidMaxisHomeFibre.SubMenu.Input': API.DiscoverMaxisProductsServices_SwitchtoMaxisPostpaidMaxisHomeFibre_SubMenu_Input,
    'DiscoverMaxisProductsServices.SwitchtoMaxisPostpaidMaxisHomeFibre.SubMenu.Input1': API.DiscoverMaxisProductsServices_SwitchtoMaxisPostpaidMaxisHomeFibre_SubMenu_Input1,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPostpaid.SubMenu.Input': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPostpaid_SubMenu_Input,
    'DiscoverMaxisProductsServices.SwitchtoHotlinkPrepaid.SubMenu.Input': API.DiscoverMaxisProductsServices_SwitchtoHotlinkPrepaid_SubMenu_Input,
    'PortIn.MaxisPostpaid.LMSCRMLeadCreation': API.PortIn_MaxisPostpaid_LMSCRMLeadCreation,
    'PortIn.MaxisPostpaid.ContactNumber.OtherMSISDN.Verify': API.PortIn_MaxisPostpaid_ContactNumber_OtherMSISDN_Verify,
    'PortIn.MaxisHomeFibre.LMSCRMLeadCreation': API.PortIn_MaxisHomeFibre_LMSCRMLeadCreation,
    'PortIn.MaxisHomeFibre.ContactNumber.OtherMSISDN.Verify': API.PortIn_MaxisHomeFibre_ContactNumber_OtherMSISDN_Verify,
    'PortIn.HotlinkPostpaid.LMSCRMLeadCreation': API.PortIn_HotlinkPostpaid_LMSCRMLeadCreation,
    'PortIn.HotlinkPostpaid.ContactNumber.OtherMSISDN.Verify': API.PortIn_HotlinkPostpaid_ContactNumber_OtherMSISDN_Verify,
    'PortIn.HotlinkPrepaid.LMSCRMLeadCreation': API.PortIn_HotlinkPrepaid_LMSCRMLeadCreation,
    'PortIn.HotlinkPrepaid.ContactNumber.OtherMSISDN.Verify': API.PortIn_HotlinkPrepaid_ContactNumber_OtherMSISDN_Verify,
    // PTP
    'Payment.PaymentArrangement.PTP': API.Payment_PaymentArrangement_PTP,
    'Payment.PaymentArrangement.PTP.SetUp.Yes': API.Payment_PaymentArrangement_PTP_SetUp_Yes,

    // Locate Payment
    'Billing.AccountStatus.LocatePayment': API.Billing_AccountStatus_LocatePayment,
    'Billing.AccountStatus.LocatePayment.OpenCase.No.WithAttachment': API.Billing_AccountStatus_LocatePayment_OpenCase_No_WithAttachment,
    'Attachment.Check': API.Attachment_Check,
    'LocatePayment.AddAttachment': API.LocatePayment_AddAttachment,
    // "Payment.LocatePayment.ExistingOpenCase.No.AttachmentSize" : API.Payment_LocatePayment_ExistingOpenCase_No_WithAttachment

    // OLO Authentication
    'OLO.authentication': API.OLO_authentication,
    'olo.authentication.yes.NRICinput': API.olo_authentication_yes_input,
    'olo.authentication.no.Passportinput': API.olo_authentication_no_Passportinput,
    'Greeting.Authentication.OLO.VerifyCBR': API.olo_authentication_VerifyCBR,
    'Greeting.Authentication.OLO.VerifyCBRFailed.FibreAccInput': API.OLO_VerifyCBRFailed_FibreAccInput,
    // "Greeting.Authentication.OLO.OfferUpdateCBR.yes" : API.OLO_VerifyFibreAccPassed_UpdateCBR_yes,
    // "Greeting.Authentication.OLO.OfferUpdateCBR.no" : API.OLO_VerifyFibreAccPassed_UpdateCBR_no,
    // "Greeting.Authentication.OLO.VerifyTAC": API.Greeting_Authentication_OLO_VerifyTAC,
    'ManageRouter.Start.Reboot.ChangeWifi-OLO': API.ManageRouter_Start_changeWifi,
    'ManageRouter.Start.Reboot.RouterReboot.OLO': API.ManageRouter_Start_Reboot,

    'Authentication.OLO.Multichannel.Query': API.Authentication_OLO_Multichannel_Query,
    'authentication.olo.nric.query': API.Authentication_OLO_Multichannel_NRIC_Query,
    'authentication.olo.pass.query': API.Authentication_OLO_Multichannel_Passport_Query,
    'Authentication.OLO.VerifyCBRFailed.Query': API.Authentication_OLO_Multichannel_VerifyCBRFailed_FibreAccInput,


    // -----------------------------------------------------//
    //             MaxBotIdle Maxis PostPaid     338-383  //
    // ---------------------------------------------------//
    // DeviceDiscoveryMaxisPostpaid
    'MaxBotIdle.Sales.PurchaseDevice.LatestPromo': API.MaxBotIdle_Sales_PurchaseDevice_LatestPromo,
    'MaxBotIdle.Sales.PurchaseDevice.LatestDevice': API.MaxBotIdle_Sales_PurchaseDevice_LatestDevice,
    'MaxBotIdle.Maxis.Postpaid.ExploreAllDevices.Query': API.Maxis_Postpaid_ExploreAllDevices_Query_new,
    'MaxBotIdle.Maxis.Postpaid.ExploreAllDevices.Query.Tablet': API.Maxis_Postpaid_ExploreAllDevices_Query_new,
    'MaxBotIdle.Maxis.Postpaid.SelectionByContract.Query': API.Maxis_Postpaid_SelectionByContract_Query,
    'MaxBotIdle.Maxis.Postpaid.ExploreAllDevices.Query.Wear': API.Maxis_Postpaid_ExploreAllDevices_Query_new,
    'MaxBotIdle.Maxis.Postpaid.SelectionByPromo.Query': API.Maxis_Postpaid_SelectionByPromo_Query,
    'MaxBotIdle.Maxis.Postpaid.SelectionByBrand.Query': API.Maxis_Postpaid_SelectionByBrand_Query,
    'MaxBotIdle.Maxis.Postpaid.SelectionByContract.Brands.Query': API.Maxis_Postpaid_SelectionByContract_Brands_Query,
    'MaxBotIdle.Maxis.Postpaid.SelectionByPromo.Brands.Query': API.Maxis_Postpaid_SelectionByPromo_Brands_Query,
    'MaxBotIdle.Maxis.Postpaid.SelectionByContract.Models.Query': API.Maxis_Postpaid_SelectionByContract_Models_Query,
    'MaxBotIdle.Maxis.Postpaid.SelectionByPromo.Models.Query': API.Maxis_Postpaid_SelectionByPromo_Models_Query,
    'MaxBotIdle.Maxis.Postpaid.ModelSelectionByBrand.Query': API.Maxis_Postpaid_ModelSelectionByBrand_Query,
    'MaxBotIdle.Maxis.Postpaid.CapacitySelectionByBrand.Query': API.Maxis_Postpaid_CapacitySelectionByBrand_Query,
    'MaxBotIdle.Maxis.Postpaid.ColorSelectionByBrand.Query': API.Maxis_Postpaid_ColorSelectionByBrand_Query,
    'MaxBotIdle.Maxis.Postpaid.ContractSelectionByBrand.Query': API.Maxis_Postpaid_ContractSelectionByBrand_Query,
    'MaxBotIdle.Maxis.Postpaid.RatePlanSelectionByBrand.Query': API.Maxis_Postpaid_RatePlanSelectionByBrand_Query,
    'MaxBotIdle.Greeting.DeviceDiscoverAndPurchase.Query': API.Greeting_DeviceDiscoverAndPurchase_Query,
    'DeviceDiscovery.Closure.Query': API.DeviceDiscovery_Closure_Query,



    // bot sales flow maxis postpaid
    'MaxBotIdle.DiscoverMaxisProductServices.Device.MainMenu.Query': API.DiscoverMaxisProductServices_Device_MainMenu_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Principal.PlanSelection.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Principal_PlanSelection_Query,
    'DiscoverMaxisProductServices.Postpaid.MobilePlan.DTS.Callback.END.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_DTS_Callback_END_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Supplementary.PlanSelection.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Supplementary_PlanSelection_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Family.PlanSelection.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Family_PlanSelection_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.HomeFibre.PlanType.Query': API.DiscoverMaxisProductServices_Postpaid_HomeFibre_PlanType_Query,
    'DiscoverMaxisProductServices.Postpaid.BroadbandHome.DTS.Callback.END.Query': API.DiscoverMaxisProductServices_Postpaid_BroadbandHome_DTS_Callback_END_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.Broadband.PlanType.Query': API.DiscoverMaxisProductServices_Postpaid_Broadband_PlanType_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.BroadbandHome.Family.PlanType.Query': API.DiscoverMaxisProductServices_Postpaid_BroadbandHome_Family_PlanType_Query,
    'DiscoverMaxisProductServices.Postpaid.Device.DTS.Callback.END.Query': API.DiscoverMaxisProductServices_Postpaid_Device_DTS_Callback_END_Query,
    'DiscoverMaxisProductServices.Postpaid.MobilePlan.CheckOut.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_CheckOut_Query,
    'DiscoverMaxisProductServices.Device.CheckOutLink.Query': API.DiscoverMaxisProductServices_Device_CheckOutLink_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Principal.RegisterType.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Principal_RegisterType_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Supplementary.RegisterType.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Supplementary_RegisterType_Query,
    'DiscoverMaxisProductServices.Device.CheckOutLink.Query2': API.DiscoverMaxisProductServices_Device_CheckOutLink_Query2,
    'MaxBotIdle.DiscoverMaxisProductServices.PostpaidBroadband.Menu.Query': API.MaxbotIdle_DiscoverMaxisProductServices_PostpaidBroadband_Menu_Query,
    'MaxBotIdle.Devices.Telesales.Query': API.MaxbotIdle_Devices_Telesales_Query,
    'MaxBotIdle.DeviceDiscovery.RatePlanMenu.Query': API.DeviceDiscovery_RatePlanMenu_Query,
    'MaxBotIdle.DeviceDiscovery.RatePlan.Checkout.Query': API.DeviceDiscovery_RatePlan_Checkout_Query,
    'MaxBotIdle.DeviceDiscovery.RatePlan.Telesales1.Query': API.DeviceDiscovery_RatePlan_Telesales1_Query,
    'MaxBotIdle.DeviceDiscovery.RatePlan.Telesales2.Query': API.DeviceDiscovery_RatePlan_Telesales2_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.Family.DTS.PreferredContact.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_Family_DTS_PreferredContact_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.BroadbandHome.DTS.PreferredContact.Query': API.DiscoverMaxisProductServices_Postpaid_BroadbandHome_DTS_PreferredContact_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.MobilePlan.FamilyPlan.DTS.PreferredContact.Query': API.DiscoverMaxisProductServices_Postpaid_MobilePlan_FamilyPlan_DTS_PreferredContact_Query,
    'MaxBotIdle.DeviceDiscovery.Wifi.CheckOut.Query': API.DeviceDiscovery_Wifi_CheckOut_Query,
    'DeviceDiscovery.Wifi.PreferredContact.Query': API.DeviceDiscovery_Wifi_PreferredContact_Query,
    'DeviceDiscovery.Family.LMS.Query': API.DeviceDiscovery_Family_LMS_Query,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid.BroadbandHomeFibre.PlanSelection.Query': API.DiscoverMaxisProductServices_Postpaid_BroadbandHomeFibre_PlanSelection_Query,

    'Sales.PurchaseDevice.LatestPromo': API.Sales_PurchaseDevice_LatestPromo,
    'Sales.PurchaseDevice.LatestDevice': API.Sales_PurchaseDevice_LatestDevice,

    // ----------------------------------------------------//
    //              HotlinkPostPaid                       //
    // ----------------------------------------------------//
    'Shared.MainMenuTelesales': API.Shared_MainMenuStart,
    'Shared.Idle.AgentAssist - yes': API.Shared_Idle_AgentAssit_Telesales,
    'Shared.Idle.AgentAssist - no': API.Idle_AgentAssist_verify,
    'DiscoverMaxisProductServices.Menu.Input': API.DiscoverMaxisProductServices_Menu_Input,
    'MaxBotIdle.Sales.DiscoverMaxisProductServices.HotlinkPostpaid.Menu.Input': API.Sales_DiscoverMaxisProductServices_HotlinkPostpaid_Menu_Input,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.DeviceDiscovery': API.DiscoverMaxisProductServices_HotlinkPostpaid_DeviceDiscovery,
    'DiscoverMaxisProductServices.HotlinkPostpaid.DeviceDiscovery.DTS.PhoneCall': API.DiscoverMaxisProductServices_HotlinkPostpaid_DeviceDiscovery_DTS_PhoneCall,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.BrandSelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_BrandSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.PromoSelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_PromoSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.LatestPromo': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_LatestPromo,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.LatestDevices': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_LatestDevices,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.ExploreInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_ExploreInput,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.LatestPromoExploreDeviceYesInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_LatestPromoExploreDeviceYesInput,
    'MaxBotIdle.DiscoverMaxisProductServices.Postpaid&Broadband.Device.BrandSelection': API.DiscoverMaxisProductServices_Postpaid_Broadband_Device_BrandSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.CapacitySelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_CapacitySelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.ColourSelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_ColourSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.ColorSelected': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_ColorSelected,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MobileRatePlans': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobileRatePlans,
    'DiscoverMaxisProductServices.HotlinkPostpaid.MobileRatePlan.DTS.PhoneCall': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobileRatePlan_DTS_PhoneCall,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MobilePlan.CheckOutCallbackSignupWA_PhInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobilePlan_CheckOutCallbackSignupWA_PhInput,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MRP.DTS.PreferredContactInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_MRP_DTS_Preferred_ContactInput,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MobilePlan.CheckOutCallbackOptionsInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobilePlan_CheckOutCallbackOptionsInput,
    'DiscoverMaxisProductServices.HotlinkPostpaid.MobilePlan.CheckOutCallbackSignupNewNumber': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobilePlan_CheckOutCallbackSignupNewNumber,
    'DiscoverMaxisProductServices.HotlinkPostpaid.MobileRatePlan.UpgradeHotlinkPrepaid.Call': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobileRatePlan_UpgradeHotlinkPrepaid_PhoneCall,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MobileRatePlan.UpgradeHotlinkPrepaidInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobileRatePlan_UpgradeHotlinkPrepaidInput,
    'DiscoverMaxisProductServices.HotlinkPostpaid.MobilePlan.CheckOut': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobilePlan_CheckOut,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPlanInput': API.DiscoverMaxisProductServices_HotlinkPostpaid_BroadbandPlanInput,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPlan.Broadband': API.DiscoverMaxisProductServices_HotlinkPostpaid_BroadbandPlan_Broadband,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPlan.BroadbandSelected': API.DiscoverMaxisProductServices_HotlinkPostpaid_BroadbandPlan_BroadbandSelected,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPlan.Bundled': API.DiscoverMaxisProductServices_HotlinkPostpaid_BroadbandPlan_Bundled,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPlan.BundledSelected': API.DiscoverMaxisProductServices_HotlinkPostpaid_BroadbandPlan_BundledSelected,
    'DiscoverMaxisProductServices.HotlinkPostpaid.BundledPlanPhonecall': API.DiscoverMaxisProductServices_HotlinkPostpaid_BundledPlanPhonecall,
    'DiscoverMaxisProductServices.HotlinkPostpaid.BroadbandPhoneCall': API.DiscoverMaxisProductServices_HotlinkPostpaid_BradbandPhoneCall,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.RatePlantSelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_RatePlantSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.SKUSummary': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_SKUSummary,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.DeviceDiscovery.DTS.Preferred.Contact.Input': API.DiscoverMaxisProductServices_HotlinkPostpaid_DeviceDiscovery_WA_Ph_Input_Menu,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.PromoBrandSelection': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_PromoBrandSelection,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.PromoBrandSelected': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_PromoBrandSelected,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.MobileRatePlanSelected': API.DiscoverMaxisProductServices_HotlinkPostpaid_MobileRatePlanSelected,
    'DiscoverMaxisProductServices.DeviceDiscovery.DeviceURL': API.DiscoverMaxisProductServices_DeviceDiscovery_DeviceURL,
    'MaxBotIdle.DiscoverMaxisProductServices.Device.ProceedCheckOut': API.DiscoverMaxisProductServices_Device_ProceedCheckOut,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.OutofStock.NotifyMe.ExploreDevice': API.DiscoverMaxisProductServices_HotlinkPostpaid_OutofStock_NotifyMe_ExploreDevice,

    // Hotlink Prepaid
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPrepaid.Menu.Input': API.MaxBotIdle_DiscoverMaxisProductServices_HotlinkPrepaid_Menu_Input,
    'MaxBotIdle.HotlinkPrepaid.MobileRatePlanInfo': API.MaxBotIdle_HotlinkPrepaid_MobileRatePlanInfo,
    'MaxBotIdle.HotlinkPrepaid.SwitchInfo': API.MaxBotIdle_HotlinkPrepaid_SwitchInfo,
    'DiscoverMaxisProductServices.HotlinkPrepaid.PlanType.wh': API.DiscoverMaxisProductServices_HotlinkPrepaid_PlanType_wh,
    'DiscoverMaxisProductServices.HotlinkPrepaid..SwitchtoHotlinkPrepaid.wh': API.DiscoverMaxisProductServices_HotlinkPrepaid__SwitchtoHotlinkPrepaid_wh,

    // //Check Device Stock - intent mapper
    // "DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.Channel.Store": API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_Channel_Store,
    // "DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.Channel.Online": API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_Channel_Online,
    // "DiscoverMaxisProductServices.PostpaidBroadband.Device.CheckDeviceStock.PreferredAddress.Billing": API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_PreferredAddress_Billing,
    // "Coordinates.Check" : API.Coordinates_Check,
    // "MaxBotIdle.DiscoverMaxisProductServices.CheckDeviceStock.MaxisCentreSelection.Input" : API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_CheckDeviceStock_MaxisCentreSelection_Input,
    // "DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.OfferProceedStore" : API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_CheckDeviceStock_OfferProceedStore,
    // "DiscoverMaxisProductServices.PostpaidBroadban.Device.CheckDeviceStock.Address.ManualInput.Wh" : API.DiscoverMaxisProductServices_PostpaidBroadban_Device_CheckDeviceStock_Address_ManualInput_Wh,
    // "DiscoverMaxisProductServices.Postpaid.MaxBotIdle.DTS.WA": API.DiscoverMaxisProductServices_Postpaid_MaxBotIdle_DTS_WA,
    // "DiscoverMaxisProductServices.Postpaid.Device.CheckDeviceStock.DropPIN.NoStores.AnotherAddress.WH": API.DiscoverMaxisProductServices_Postpaid_Device_CheckDeviceStock_DropPIN_NoStores_AnotherAddress_WH,
    // "MaxbotIdle.Postpaid.CheckDeviceStock.ContractSelection": API.MaxbotIdle_Postpaid_CheckDeviceStock_ContractSelection,
    'Manage.MyVas.Query': API.Manage_MyVas_Query,
    'ManageDigitalSpendLimit.Verification': API.Manage_DigitalSpendLimit_Query,
    'ManageDigitalSpendLimit.AccountInfo': API.Shared_Closure_Entry,
    // Check Device Stock - intent mapper
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.Channel.Store': API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_Channel_Store,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.Channel.Online': API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_Channel_Online,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.CentreAddressDetails.NotNow': API.CheckDeviceStockClosingNotRightNow,
    'DiscoverMaxisProductServices.PostpaidBroadband.Device.CheckDeviceStock.PreferredAddress.Billing': API.DiscoverMaxisProductServices_PostpaidBroadband_Device_CheckDeviceStock_PreferredAddress_Billing,
    'Coordinates.Check': API.Coordinates_Check,
    'MaxBotIdle.DiscoverMaxisProductServices.CheckDeviceStock.MaxisCentreSelection.Input': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_CheckDeviceStock_MaxisCentreSelection_Input,
    'MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.CheckDeviceStock.OfferProceedStore': API.DiscoverMaxisProductServices_HotlinkPostpaid_Device_CheckDeviceStock_OfferProceedStore,
    'DiscoverMaxisProductServices.PostpaidBroadban.Device.CheckDeviceStock.Address.ManualInput.Wh': API.DiscoverMaxisProductServices_PostpaidBroadban_Device_CheckDeviceStock_Address_ManualInput_Wh,
    'DiscoverMaxisProductServices.Postpaid.MaxBotIdle.DTS.WA': API.DiscoverMaxisProductServices_Postpaid_MaxBotIdle_DTS_WA,
    'DiscoverMaxisProductServices.Postpaid.Device.CheckDeviceStock.DropPIN.NoStores.AnotherAddress.WH': API.DiscoverMaxisProductServices_Postpaid_Device_CheckDeviceStock_DropPIN_NoStores_AnotherAddress_WH,
    'MaxbotIdle.Postpaid.CheckDeviceStock.ContractSelection': API.MaxbotIdle_Postpaid_CheckDeviceStock_ContractSelection,
    // "DiscoverMaxisProductServices.MaxisPostpaid.OnlineStock" :API.DiscoverMaxisProductServices_MaxisPostpaid_OnlineStock,

    // Notifyme
    'DiscoverMaxisProduct.PostpaidBroadband.CheckDeviceStock.AcceptNotifyMe.ContactNo': API.DiscoverMaxisProduct_PostpaidBroadband_CheckDeviceStock_AcceptNotifyMe_ContactNo_Wh,
    // "DiscoverMaxisProduct.PostpaidBroadband.CheckDeviceStock.AcceptNotifyMe.ContactNo.wh" : API.DiscoverMaxisProduct_PostpaidBroadband_CheckDeviceStock_AcceptNotifyMe_ContactNo_Wh,

    // Intent for Check device delivery Status
    'Maxis.CheckMyDeliveryStatus.Start': API.Maxis_CheckMyDeliveryStatus_Start,
    'HotlinkPostPaid.CheckMyDeliveryStatus.Start': API.HotlinkPostPaid_CheckMyDeliveryStatus_Start,
    'HotlinkPrePaid.CheckMyDeliveryStatus.Start': API.HotlinkPrePaid_CheckMyDeliveryStatus_Start,

    // Prepaid Unblock TopUp Access
    'TopUp.Unblock.NumberQuery1': API.TopUp_Unblock_NumberQuery1_Auth,
    'Topup.unblock.ownnumber.selection': API.Prepaid_Unblock_Topup_Own_Number_Confirm,
    'TopUp.Unblock.OwnNo.voms.CheckStatus': API.Prepaid_Unblock_Topup_Own_Number,
    'TopUp.Unblock.OtherNo.Verification': API.Prepaid_Unblock_Topup_Other_Number,
    'TopUp.OfferTopUpMenu1': API.Prepaid_Unblock_TopUp_Own_number_Offer_Link,
    'TopUp.OfferTopUpMenu2': API.Prepaid_Unblock_TopUp_Other_Number_Offer_Link,


    // Intent for Hybrid Bot Added by Arpit
    'Hybrid.DiscoveryAndPurchase.ExploreALLDevices': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.brand': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.model': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.memory': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.color': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.contractType': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.ratePlan': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'followupevent.completed': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.brand': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.model': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.memory': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.color': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.contractType': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'provides.ratePlan': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'PayMaxisBilllHybrid': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'Hybrid.MovingTo.PayMyBills - no': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'Hybrid.MovingTo.PayMyBills - yes': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    'PreviousMenu': API.Hybrid_DiscoveryAndPurchase_ExploreALLDevices,
    // "AgentHandover.Sentiment.AgentAssist.Offer.No":API.Greeting_Start
    'AgentHandover.Sentiment.AgentAssist.Offer.No': API.AgentHandover_Sentiment_AgentAssist_Offer_No,
    'AgentHandover.Sentiment.AgentAssist.Offer.Yes': API.AgentHandover_Sentiment_AgentAssist_Offer_Yes,
    // "AgentHandover.Sentiment.AgentAssist.Offer"
    // "Bypass Bot -  AgentHandover.Sentiment.AgentAssist.Offer.Yes.Online
    // "AgentHandover.Sentiment.AgentAssist.Offer.No"
    // "followupevent.color - fallback"
    // "followupevent.contractType - fallback"
    // "followupevent.memory - fallback"
    // "followupevent.completed" -replaced with- "MaxBotIdle.DiscoverMaxisProductServices.HotlinkPostpaid.Device.SKUSummaryOutput"

    // followupevent.brandMenuList
    // followupevent.ModelMenuList
    // followupevent.MemoryMenuList
    // followupevent.ColorMenuList
    // followupevent.ContractTypeMenuList
    // followupevent.RatePlanMenuList
    //
    // Hybrid.MovingTo.PayMyBills
    //
    // _____________________________________

    // Intent for Knowledge Crawler
    'Knowledge.KnowledgeBase.ODc4NDUzNTUwNTczMjYzMjU3Ng': API.KnowledgeCrawler_Continue_Maxis,
    'Knowledge.KnowledgeBase.NTQxMjM3MjkyNTc2MjI0MDUxMg': API.KnowledgeCrawler_Continue_Hotlink,
    'FAQ.Enquiry.Maxis.Start': API.KnowledgeCrawler_Maxis_Start,
    'FAQ.Enquiry.Hotlink.Start': API.KnowledgeCrawler_Hotlink_Start,
    'FAQ.Restart.Maxis': API.KnowledgeCrawler_Maxis_Start,
    'FAQ.Restart.Hotlink': API.KnowledgeCrawler_Hotlink_Start,
    'FAQ.AnswerProvided.Yes.Maxis.Yes': API.KnowledgeCrawler_Restart,
    'FAQ.AnswerProvided.Yes.Maxis.No': API.Shared_Closure_Entry,
    'FAQ.AnswerProvided.No.Maxis.Yes': API.KnowledgeCrawler_Maxis_Yes,
    'FAQ.AnswerProvided.No.Maxis.No': API.Shared_Closure_Entry,
    'FAQ.AnswerProvided.Yes.Hotlink.Yes': API.KnowledgeCrawler_Restart,
    'FAQ.AnswerProvided.Yes.Hotlink.No': API.Shared_Closure_Entry,
    'FAQ.AnswerProvided.No.Hotlink.Yes': API.KnowledgeCrawler_Hotlink_Yes,
    'FAQ.AnswerProvided.No.Hotlink.No': API.Shared_Closure_Entry,
    'FAQ.RetrieveSuccessful.No.Maxis.Yes': API.KnowledgeCrawler_Maxis_Yes,
    'FAQ.RetrieveSuccessful.No.Maxis.No': API.Shared_Closure_Entry,
    'FAQ.RetrieveSuccessful.No.Hotlink.Yes': API.KnowledgeCrawler_Hotlink_Yes,
    'FAQ.RetrieveSuccessful.No.Hotlink.No': API.Shared_Closure_Entry,
    'FAQ.RetrieveSuccessful.No.Maxis.Webhook': API.KnowledgeCrawler_NoAnswer_Maxis,
    'FAQ.RetrieveSuccessful.No.Hotlink.Webhook': API.KnowledgeCrawler_NoAnswer_Hotlink,

    'Knowledge.Crawler.Selected': API.KnowledgeCrawler_Selected,
    'Knowledge.Crawler.Response.Yes': API.KnowledgeCrawler_Yes,
    'Knowledge.Crawler.Response.No': API.KnowledgeCrawler_No,
    'Knowledge.Crawler.Attachment.Check': API.KnowledgeCrawler_Attachment_Check,
    'Knowledge.Crawler.Webhook': API.KnowledgeCrawler_Webhook,

    // Intents for Closure (CXM Dashboarding Fix)
    'Billing.AccountStatus.LocatePaymentReceipt.CaseCreation': API.Shared_Closure_Entry,
    'Billing.AccountStatus.LocatePaymentReceipt.ExistingCaseOpen': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.ExistingCase': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.Itemised.CaseCreation': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.QueryEBill.CaseCreation': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.QueryEBill.Yes': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.Summarised.CaseCreation': API.Shared_Closure_Entry,
    'Billing.BillStatementRequest.Summarised.OfferItemised.MaxisSelfServe': API.Shared_Closure_Entry,
    'Billing.ChangeBillCycle.CaseCreation': API.Shared_Closure_Entry,
    'Billing.ChangeBillCycle.ExistingCase': API.Shared_Closure_Entry,
    'Billing.ChangeCreditLimit.CaseCreation': API.Shared_Closure_Entry,
    'Billing.ChangeCreditLimit.CurrentCreditLimit.ExistingCase': API.Shared_Closure_Entry,
    'Billing.Content.Apple': API.Shared_Closure_Entry,
    'Billing.Content.Google': API.Shared_Closure_Entry,
    'Billing.Content.Huawei': API.Shared_Closure_Entry,
    'Billing.DirectDebit.No-SignupNo': API.Shared_Closure_Entry,
    'Billing.DirectDebit.No-SignupYes': API.Shared_Closure_Entry,
    'Billing.DirectDebit.Redirectlink': API.Shared_Closure_Entry,
    'Billing.DirectDebit.RedirectNo': API.Shared_Closure_Entry,
    'Billing.eBill.CurrentEmail.End': API.Shared_Closure_Entry,
    'Billing.MakePayment.DirectDebitOffer.Yes.Wh': API.Shared_Closure_Entry,
    'Billing.MakePayment.Link': API.Shared_Closure_Entry,
    'Billing.PayBill.Other.Payment': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.EmailQuery.CaseCreated': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.ExistingCase': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.NoEbill.CaseCreated': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.NoEbill.EmailAddress.Duplicate': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.NoEbill.EmailAddress.Submited': API.Shared_Closure_Entry,
    'Billing.TaxStatementRequest.PendingEbill': API.Shared_Closure_Entry,
    'Case.Status.Check.Error': API.Shared_Closure_Entry,
    'Case.Status.Check.ExistingCase.ToDelete': API.Shared_Closure_Entry,
    'Case.Status.Check.NoCase': API.Shared_Closure_Entry,
    'CaseStatus.Details.NonFibre': API.Shared_Closure_Entry,
    'CaseStatus.NoCase': API.Shared_Closure_Entry,
    'CheckCaseStatus.TroubleshootMobile.Query': API.CheckCaseStatus_TroubleshootMobile_Query,
    'ChangeWifi.Setting.FibreAccountSelect.RedirectFSSPMicrosite': API.Shared_Closure_Entry,
    'CheckCaseStatus.TroubleshootMobile': API.Shared_Closure_Entry,
    'Closing.Menu.ExploreOtherServices': API.Shared_Closure_Entry,
    'Closing.Menu.ExploreOtherServices2': API.Shared_Closure_Entry,
    'Closing.Menu.ExploreOtherServices3': API.Shared_Closure_Entry,
    'Closing.Menu.ExploreOtherServices5': API.Shared_Closure_Entry,
    'DeviceDiscovery.Closure': API.Shared_Closure_Entry,
    'DiscoverMaxis.PostpaidBroadband.CheckDeviceStock.AcceptNotifyMe.UpdateOnlineStoreDB': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.Device.CheckOutLink': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.Device.CheckOutLink2': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.DeviceDiscovery.DeviceURL.END': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Bundled.Broadband.LeadsSuccesfull': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.LatestPromoDeviceExploreDeviceNo': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.OutofStock.NotifyMeNothingRightNow': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.Device.SKUSummary.NoCheckout': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.DTS.Callback.MoblileRatePlan.END': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPostpaid.MobilePlan.CheckOut.HOSURL': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPrepaid..HotlinkPrepaidMobileRatePlan.CheckOut': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.HotlinkPrepaid..SwitchtoHotlinkPrepaid.CheckOut': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.MaxisPostpaid.Device.OutofStock.NotifyMeNothingRightNow': API.Shared_Closure_Entry,
    'DiscoverMaxisProductServices.Postpaid.MobilePlan.CheckOut': API.Shared_Closure_Entry,
    'Greeting.Authentication.OLO.VerifyCBRFailed.VerifyFibreAccFailed': API.Shared_Closure_Entry,
    'Greeting.MainMenu.JaringanPrihatin.Profile.OfferSelection.Plan.HotlinkPrepaid-BM': API.Shared_Closure_Entry_BM,
    'Greeting.MainMenu.JaringanPrihatin.Profile.OfferSelection.Plan.HotlinkPrepaid-ENG': API.Shared_Closure_Entry,
    'Greeting.MainMenu.JaringanPrihatin.Profile.OfferSelection.Plan.Postpaid-BM': API.Shared_Closure_Entry_BM,
    'Greeting.MainMenu.JaringanPrihatin.Profile.OfferSelection.Plan.Postpaid-ENG': API.Shared_Closure_Entry,
    'HotlinkPostPaid.CheckMyDeliveryStatus.Start.Display': API.Shared_Closure_Entry,
    'HotlinkPrePaid.CheckMyDeliveryStatus.Start.Display': API.Shared_Closure_Entry,
    'iPhone13.Bm.CheckStatus': API.Shared_Closure_Entry_BM,
    'iPhone13.Bm.Faq1': API.Shared_Closure_Entry_BM,
    'iPhone13.Bm.Faq2': API.Shared_Closure_Entry_BM,
    'iPhone13.Bm.Faq3': API.Shared_Closure_Entry_BM,
    'iPhone13.Bm.Faq4': API.Shared_Closure_Entry_BM,
    'iPhone13.Bm.Model': API.Shared_Closure_Entry_BM,
    'iPhone13.En.CheckStatus': API.Shared_Closure_Entry,
    'iPhone13.En.Faq1': API.Shared_Closure_Entry,
    'iPhone13.En.Faq2': API.Shared_Closure_Entry,
    'iPhone13.En.Faq3': API.Shared_Closure_Entry,
    'iPhone13.En.Faq4': API.Shared_Closure_Entry,
    'iPhone13.En.Model': API.Shared_Closure_Entry,
    'iPhone14.SubMenu.FAQ': API.Shared_Closure_Entry,
    'iPhone14.SubMenu.Offer': API.Shared_Closure_Entry,
    'iPhone14.SubMenu.Order': API.Shared_Closure_Entry,
    'JaringanPrihatin.Bm.ClaimSubsidy.PostpaidWifi.Claim': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.ClaimSubsidy.PostpaidWifi.Register': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.ClaimSubsidy.Prepaid.Claim': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.ClaimSubsidy.Prepaid.Register': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.No': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.PostpaidWifi.Claim': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.PostpaidWifi.Redeem': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.PostpaidWifi.Register': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.Prepaid.Claim': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.Prepaid.Redeem': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.BillRebate.Prepaid.Register': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.Eligible.Yes.DeviceSubsidy.CreateCase': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.NonMaxis.Eligible.No': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.NonMaxis.Eligible.Yes.CreateLeads': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.NonMaxis.Eligible.Yes.ExistingCase': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.RedeemData.PostpaidWifi': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Bm.RedeemData.Prepaid': API.Shared_Closure_Entry_BM,
    'JaringanPrihatin.Eligible.No': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.PostpaidWifi.Claim': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.PostpaidWifi.Redeem': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.PostpaidWifi.Register': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.Prepaid.Claim': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.Prepaid.Redeem': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.BillRebate.Prepaid.Register': API.Shared_Closure_Entry,
    'JaringanPrihatin.Eligible.Yes.DeviceSubsidy.CreateCase': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.ClaimSubsidy.PostpaidWifi.Claim': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.ClaimSubsidy.PostpaidWifi.Register': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.ClaimSubsidy.Prepaid.Claim': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.ClaimSubsidy.Prepaid.Register': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.RedeemData.PostpaidWifi': API.Shared_Closure_Entry,
    'JaringanPrihatin.English.RedeemData.Prepaid': API.Shared_Closure_Entry,
    'JaringanPrihatin.NonMaxis.Eligible.No': API.Shared_Closure_Entry,
    'JaringanPrihatin.NonMaxis.Eligible.Yes.CreateLeads': API.Shared_Closure_Entry,
    'JaringanPrihatin.NonMaxis.Eligible.Yes.ExistingCase': API.Shared_Closure_Entry,
    'Manage.MyVas.Output.Hotlink': API.Shared_Closure_Entry,
    'Manage.MyVas.Output': API.Shared_Closure_Entry,
    'Maxis.CheckMyDeliveryStatus.Start.Display': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.Coverage': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.Devices': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.Pass': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.Plans': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.Roaming': API.Shared_Closure_Entry,
    'Maxis5G.Submenu.SIM': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.1.1': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.1.2': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.1.3': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.2.1': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.2.2': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.2.3': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.2.4': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.3.1': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.3.2': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.4.1': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.5.1': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.5.2': API.Shared_Closure_Entry,
    'Network.Fibre.Guide.5.3': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceNo.Notify': API.Shared_Closure_Entry,
    //'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceYes.Notify': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.ExistingCase': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.NoFibreService': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.PositiveResult.Assistance-Yes': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.PositiveResult.Assistance.No.END': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Nok.HasCase': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Ok.GoodSignal.With2.4Ghz': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Ok.PoorSignal.With2.4Ghz': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Ok.TooManyDevices.Duplicate': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.Result.Ok.WrongFrequency.With2.4Ghz': API.Shared_Closure_Entry,
    'Network.Fibre.SlowWifi.DiagnosticCheck.RouterOffline': API.Shared_Closure_Entry,
    'Payment.PaymentArrangement.PTP.Eligible.No.ActivePTP.Yes': API.Shared_Closure_Entry,
    'Payment.PaymentArrangement.PTP.NotEligible': API.Shared_Closure_Entry,
    'Payment.PaymentArrangement.PTP.SetUp.Sucessful.Yes': API.Shared_Closure_Entry,
    'PortIn.7DayTimedOut.OpenCase': API.Shared_Closure_Entry,
    'PortIn.NoRecordFound': API.Shared_Closure_Entry,
    'PortIn.Status.InProcess.12hours.END': API.Shared_Closure_Entry,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.ActivationMoreThan2Hours.Query.No': API.Shared_Closure_Entry,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.MoreThan12Hours.Created.END': API.Shared_Closure_Entry,
    'PortIn.Status.InProcess.Maxis.CaseEscalation.MoreThan12Hours.Escalation.No': API.Shared_Closure_Entry,
    'PortIn.Status.InProcess.OLO.END': API.Shared_Closure_Entry,
    'PortIn.Status.Rejected.7DayTimedOut.lessthan7days': API.Shared_Closure_Entry,
    'PortIn.Status.Rejected.7DayTimedOut.PortIn.No': API.Shared_Closure_Entry,
    'PortIn.Status.Successful.END': API.Shared_Closure_Entry,
    'PortOut.Rejected.END': API.Shared_Closure_Entry,
    'PortOut.Status.InProcess.END': API.Shared_Closure_Entry,
    'PortOut.Status.Successful.END': API.Shared_Closure_Entry,
    'PrepaidTopup.AcceptTopup.No-yes': API.Shared_Closure_Entry,
    'PrepaidTopup.AcceptTopup.Yes.Wh': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Bangladesh.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Bangladesh.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Cambodia.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Cambodia.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.China.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.China.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.India.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.India.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Indonesia.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Indonesia.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Myanmar.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Myanmar.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Nepal.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Nepal.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Pakistan.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Pakistan.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Philippines.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Philippines.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.SriLanka.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.SriLanka.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Thailand.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Thailand.SMS': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Vietnam.EM': API.Shared_Closure_Entry,
    'PrepaidTopup.iShare.FAQ.Vietnam.SMS': API.Shared_Closure_Entry,
    // 'PrepaidTopup.TopupHistory': API.Shared_Closure_Entry,
    'PrepaidTopup.ViewEstatement-no': API.Shared_Closure_Entry,
    'Profile.BillingAddress.ChangeAddress.CaseCreation': API.Shared_Closure_Entry,
    'Profile.BillingAddress.ChangeAddress.Confirmation.Cancel': API.Shared_Closure_Entry,
    'Profile.DID.SelfServe': API.Shared_Closure_Entry,
    'Recontracting.Details': API.Shared_Closure_Entry,
    'Recontracting.Details.K2': API.Shared_Closure_Entry,
    'Recontracting.Details.NoDuration': API.Shared_Closure_Entry,
    'Recontracting.Details.Zerolution': API.Shared_Closure_Entry,
    'Recontracting.Details.Zerolution360': API.Shared_Closure_Entry,
    'RouterRebootSetting.FibreAccountSelect.RedirectFSSPMicrosite': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.DiscoveryBrand.Sku.Checkout': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.DiscoveryBrand.Sku.No': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.DiscoveryBrand.SKUSummary.ExploreOther': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.DiscoveryOffer.SKUSUmmary.Proceed.Checkout2': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.LatestDevice.End': API.Shared_Closure_Entry,
    'Sales.PurchaseDevice.LatestPromo.End': API.Shared_Closure_Entry,
    'Shared.Closure.Entry': API.Shared_Closure_Entry,
    'Shared.Closure.Entry2': API.Shared_Closure_Entry,
    'Shared.Duplicate.LMSCRMLeadSubmission': API.Shared_Closure_Entry,
    'Shared.Error.InvalidArgument': API.Shared_Closure_Entry,
    'Shared.Tech.Issue.HotlinkPostpaidSales': API.Shared_Closure_Entry,
    'Shared.Tech.IssueServicing': API.Shared_Closure_Entry,
    'Shared.Tech.IssueServicingHotlink': API.Shared_Closure_Entry,
    'Shared.Telesales.Offline': API.Shared_Closure_Entry,
    'Shared.Telesales.Online': API.Shared_Closure_Entry,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.FirstPhoto.IndicatorLights.Offline.Closure': API.Shared_Closure_Entry,
    'Manage.Billing.Tac': API.Manage_Billing_Tac,
    'Paybill.Perform.Topup.Query': API.Paybill_Perform_Topup_Query,

    'IRTR.RouterImageUploadYes': API.IRTR_RouterImageUploadYes_Check,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.Confirmation.Input': API.IRTR_Network_Fibre_Wifi_UploadRouterPhoto_Confirmation_Input,
    'IRTR.FristRouterImage.AttachmentCheck': API.IRTR_FristRouterImage_AttachmentCheck,
    // "IRTR.ResizeImage.UploadImage.GCP.Bucket": API.IRTR_ResizeImage_UploadImage_GCP_Bucket,
    'IRTR.FristRouterImage.IR.API.Start': API.IRTR_IR_API_Initiate,
    'IRTR.Network.Fibre.SlowWifi.IR.Only.CreateCase.Start': API.IRTR_Network_Fibre_SlowWifi_IR_Only_CreateCase_Start,
    'IRTR.Network.Fibre.Wifi.AttachSecondImagetoCase': API.IRTR_Network_Fibre_Wifi_AttachSecondImagetoCase_WH,
    'IRTR.Network.Fibre.SlowWifi.DiagnosticCheck.Yes.AttemptsExceeded': API.Network_Fibre_SlowWifi_DiagnosticCheck_Yes,
    'IRTR.Network.Fibre.SlowWifi.DiagnosticCheck.VirusImage':API.Network_Fibre_SlowWifi_DiagnosticCheck_Yes,

    // DiagnosticResultsWithoutImage
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.FirstPhoto.IndicatorLights.NoIR.Input': API.IRTR_Network_Fibre_Wifi_UploadRouterPhoto_FirstPhoto_IndicatorLights_NoIR_Input,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.FirstPhoto.IndicatorLights.NoIR.AttachmentCheck': API.IRTR_NoIR_FirstPhoto_AttachementCheck,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.SecondPhoto.PortSerialNo.NoIR.AttachmentCheck': API.IRTR_NoIR_SecondPhoto_AttachmentCheck,
    'IRTR.Network.Fibre.Wifi.RouterSwitchedOn.Connection.Not.Restored': API.IRTR_Network_Fibre_Wifi_RouterSwitchedOn_Connection_Not_Restored,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.ValidFirstSecondPhoto.OfferDiagnosticCheck.AttachmentCheck': API.IRTR_UploadSecondImage_DicagnotsticResults_AttachementCheck,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.FirstPhoto.IndicatorLights.NoIR.InvalidFormat':API.IRTR_DiagnosticResult_NoIR_NoFirstImage_CaseCreation_Start,
    'IRTR.Network.Fibre.Wifi.UploadRouterPhoto.SecondPhoto.PortSerialNo.NoIR.InvalidFormat':API.IRTR_DiagnosticResult_FristImage_NoSecondImage_CaseCreation_Strat,
    'IRTR.NegativeDiagnostiResult.NoIR.InvalidImage.CaseCreation':API.IRTR_NegativeDiagnotsticResult_NoIR_InvalidImageCaseCreation,
    'IRTR.Network.Fibre.SlowWifi.DiagnosticCheck.CreateCase': API.IRTR_Case_Creation_NoIR_Start,
    'IRTR.Network.Fibre.SlowWifi.DiagnosticCheck.DiagnosticError.AssistanceYes.Notify':API.Shared_Closure_Entry,
    'IRTR.Network.Fibre.SlowWifi.DiagnosticCheck.PositiveResult.Assistance.Yes.END':API.Shared_Closure_Entry,
    'Shared.Invalid.Input.IR': API.Shared_Invalid_Input_IR,
    // aboveone have to remove
    'IRTR.Network.Fibre.Wifi.DiagnosticCheckResults.NoIR.CaseCreation': API.IRTR_Network_Fibre_Wifi_DiagnosticCheckResults_NoIR_CaseCreation,

    // Manage My Other Line
    'Manage.OtherLine.Start': API.Manage_OtherLine_Start,
    'Manage.OtherLine.Principal.No': API.Shared_Closure_Entry,
    'Manage.OtherLine.Principal.Yes': API.Manage_OtherLine_Principal_Yes,
    'Manage.OtherLine.Check.Last6Digit.NRIC': API.Manage_OtherLine_Check_Last6Digit_NRIC,
    'Manage.OtherLine.Selection.Input': API.Manage_OtherLine_Switch_MSISDN
    // Manage My Other Line
  }
}
